### ISSUE TITLE
Data conversion scripts: only rely on the raw data set

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_interactive_driver#198]
Currently, the dependent time calculation works on the `raw` data set but the insert/delete (update) stream conversion script works on the BI data set. These could/should be unified on the `raw` data set.

**Comment by GLaDAP** [comment]
To only use the raw data set, the start date of the update streams (or end date of the initial_snapshot) should be known so update streams does not contain entities from the initial_snapshot. However, the cutoff creationDate is not fixed by day, for example:
- **Person:** `initial_snapshot` ends at `2012-11-29 01:35:39.214`. 1 Person is created between `2012-11-29 00:00:00.000` and `2012-11-29 01:35:39.214`.
- **Comment:** `initial_snapshot` ends `2012-11-29 02:52:16.35`. 1683 comments are created between `2012-11-29 00:00:00.000` and `2012-11-29 02:52:16.35`.

So extraction of the creationDate should be taken into account as well

**Comment by szarnyasg** [comment]
Fixed by #203
