### ISSUE TITLE
SNB/IW: Updates for the type DateTime use Date inputs instead of DateTime

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_interactive_driver#65]
Hi,

In (all?) updates issued by the driver for the SNB/IW workload, when the specification expects a DateTime as parameter type, the driver always provide an instance of java.util.Date. Basically the time is not recorded. Is this behaviour implemented on purpose?

**Comment by szarnyasg** [comment]
The specification has been revised since and none of the Interactive read queries ([complex](https://ldbcouncil.org/ldbc_snb_docs/workload-interactive-complex-reads.pdf), [short](https://ldbcouncil.org/ldbc_snb_docs/workload-interactive-short-reads.pdf)) expect a DateTime. Dates can occur on the input and some queries return a DateTime, handled as a long (UNIX epoch) by the driver.

**Comment by szarnyasg** [comment]
Actually, the inserts indeed use `Date` parameters instead of `DateTime`s. Hah! See
* https://ldbcouncil.org/ldbc_snb_docs/workload-interactive-inserts.pdf
* https://github.com/ldbc/ldbc_snb_driver/blob/4916dcdf1552b9799113ccab6cdc27d3f94104f8/src/main/java/com/ldbc/driver/workloads/ldbc/snb/interactive/LdbcUpdate1AddPerson.java#L41

**Comment by szarnyasg** [comment]
This issue is still present in the codebase: https://github.com/ldbc/ldbc_snb_interactive_driver/blob/fe5bdf7cecd7c638599b05477debfc57e34108e6/src/main/java/org/ldbcouncil/snb/driver/workloads/interactive/LdbcUpdate1AddPerson.java#L42-L43

**Comment by szarnyasg** [comment]
Looked into this in more detail. `java.util.Date` stores timestamps [with millisecond precision](https://docs.oracle.com/javase/8/docs/api/java/util/Date.html):
> The class Date represents a specific instant in time, with millisecond precision.

The code had a confusing comment and a superfluous one - I removed them.
